<?php

namespace App\Http\Controllers;

use App\Services\AppLogger;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\HtmlString;

class AiController extends Controller
{
    private const AI_DISCLAIMER = '<p class="mt-4 text-xs italic text-gray-500 dark:text-gray-500">This response was generated by AI and should be reviewed for accuracy before use.</p>';

    /**
     * Get AI-generated control checking response.
     */
    public static function getImplementationCheck($record): HtmlString
    {
        $systemPrompt = <<<'PROMPT'
        You are an experienced information security professional specializing in control implementation and compliance frameworks (SOC 2, ISO 27001, NIST, COSO, etc.).

        Your task is to determine if the implementations provided meet the requirements of the specified security control.

        Response requirements:
        - Respond with a single "Meets Requirements", "Does Not Meet Requirements", or "Partially Meets Requirements"
        - Include a justification for you response in exactly one paragraph (3-5 sentences)
        - Use plain language suitable for both technical and non-technical stakeholders
        - Reference specific tools, processes, or documentation where appropriate
        - Respond in html format with the following structure:
            <div class="space-y-4">
                <div>
                    <h4 class="text-sm font-semibold text-gray-900 dark:text-gray-100">Conclusion</h4>
                    <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">[Your conclusion here]</p>
                </div>
                <div>
                    <h4 class="text-sm font-semibold text-gray-900 dark:text-gray-100">Justification</h4>
                    <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">[Your justification here]</p>
                </div>
                <div>
                    <h4 class="text-sm font-semibold text-gray-900 dark:text-gray-100">Recommendations</h4>
                    <ul class="mt-1 text-sm text-gray-600 dark:text-gray-400 list-disc list-inside space-y-1">
                        <li>[Recommendation 1]</li>
                        <li>[Recommendation 2]</li>
                    </ul>
                </div>
            </div>
        - For any lists, use: <ul class="mt-1 text-sm text-gray-600 dark:text-gray-400 list-disc list-inside space-y-1"> with <li> items
        PROMPT;

        $implementations = json_encode($record->implementations()->pluck('details')->join("\n") ?? 'None');
        $applications = json_encode(\App\Models\Application::get()->pluck('name')->toArray());

        $userPrompt = "User has the following implementations currently: {$implementations}.
            User also has the following applications currently: {$applications}.
            Evaluate the implementations against the following security control: {$record['description']}";

        $response = self::ogChatCompletion($systemPrompt, $userPrompt);

        AppLogger::info(
            'ai',
            'ImplementationCheck',
            'AI implementation check completed',
            [
                'control_id' => $record->id,
                'model' => $response['model'],
                'prompt_tokens' => $response['usage']['prompt_tokens'] ?? null,
                'completion_tokens' => $response['usage']['completion_tokens'] ?? null,
                'total_tokens' => $response['usage']['total_tokens'] ?? null,
            ],
            $record
        );

        return new HtmlString($response['content'] . self::AI_DISCLAIMER);
    }

    /**
     * Get AI-generated implementation suggestions for a security control.
     */
    public static function getControlSuggestions($record): HtmlString
    {
        $systemPrompt = <<<'PROMPT'
        You are an experienced information security professional specializing in control implementation and compliance frameworks (SOC 2, ISO 27001, NIST, COSO, etc.).

        Your task is to provide practical, actionable implementation guidance for security controls.

        Response requirements:
        - Write exactly one paragraph (3-5 sentences)
        - Focus on concrete, implementable steps
        - Use plain language suitable for both technical and non-technical stakeholders
        - Reference specific tools, processes, or documentation where appropriate
        - Do not include headers, bullet points, or markdown formatting
        PROMPT;

        $applications = json_encode(\App\Models\Application::get()->pluck('name')->toArray());

        $userPrompt = "User has the following applications currently: {$applications}.
            Provide a sample implementation description for
            the following security control: {$record['description']}";

        return new HtmlString(self::chatCompletion($systemPrompt, $userPrompt) . self::AI_DISCLAIMER);
    }

    /**
     * Send a chat completion request to OpenAI.
     */
    protected static function chatCompletion(string $systemPrompt, string $userPrompt): string
    {
        $client = new \GuzzleHttp\Client;
        $key = Crypt::decryptString(setting('ai.openai_key'));

        $response = $client->request('POST', 'https://api.openai.com/v1/chat/completions', [
            'headers' => [
                'Content-Type' => 'application/json',
                'Authorization' => "Bearer {$key}",
            ],
            'json' => [
                'model' => 'gpt-4.1-mini',
                'store' => true,
                'messages' => [
                    [
                        'role' => 'system',
                        'content' => $systemPrompt,
                    ],
                    [
                        'role' => 'user',
                        'content' => $userPrompt,
                    ],
                ],
            ],
        ]);

        $body = $response->getBody();
        $data = json_decode($body, true);

        return $data['choices'][0]['message']['content'];
    }
    

    protected static function ogChatCompletion(string $systemPrompt, string $userPrompt): array
    {
        $client = new \GuzzleHttp\Client;
        //$key = Crypt::decryptString(setting('ai.openai_key'));
        $key = env('AI_DO_KEY', $key);

        $response = $client->request('POST', 'https://inference.do-ai.run/v1/chat/completions', [
            'headers' => [
                'Content-Type' => 'application/json',
                'Authorization' => "Bearer {$key}",
            ],
            'json' => [
                'model' => 'alibaba-qwen3-32b',
                'messages' => [
                    [
                        'role' => 'system',
                        'content' => $systemPrompt,
                    ],
                    [
                        'role' => 'user',
                        'content' => $userPrompt,
                    ],
                ],
            ],
        ]);

        $body = $response->getBody();
        $data = json_decode($body, true);

        return [
            'content' => $data['choices'][0]['message']['content'],
            'model' => $data['model'] ?? 'unknown',
            'usage' => $data['usage'] ?? [],
        ];
    }

    
}
